name: android-studio
version: latest
version-script: cat $SNAPCRAFT_STAGE/version
summary: The IDE for Android
description: |
  Android Studio provides the fastest tools for building apps on every type
  of Android device.

  World-class code editing, debugging, performance tooling, a flexible build
  system, and an instant build/deploy system all allow you to focus on
  building unique and high quality apps.

grade: stable
confinement: classic

architectures:
  - build-on: amd64

apps:
  android-studio:
    command: android-studio/bin/studio.sh
    desktop: jetbrains-studio.desktop

parts:
  gnome:
    plugin: nil
    build-packages:
      - software-properties-common
    override-pull: |
      add-apt-repository -y ppa:ubuntu-desktop/gnome-3-26
      apt -y update
      apt -y upgrade
  desktop:
    after:
      - android-studio
    plugin: dump
    source: .
    prime:
      - jetbrains-studio.desktop
  android-studio:
    after: [gnome]
    plugin: nil
    override-build: |
      snapcraftctl build
      echo "Get latest release..."
      RELEASE_INFO=$(python3 -u get_latest.py)
      VERSION=$(echo $RELEASE_INFO | cut -d ' ' -f1)
      echo $VERSION > $SNAPCRAFT_STAGE/version
      DOWNLOAD_URL=$(echo ${RELEASE_INFO} | cut -d ' ' -f2)

      wget --quiet "${DOWNLOAD_URL}" -O "${SNAPCRAFT_PART_INSTALL}/android-studio.tar.gz"
      tar -xf "${SNAPCRAFT_PART_INSTALL}/android-studio.tar.gz" -C "${SNAPCRAFT_PART_INSTALL}"

      # Cleanup
      rm "${SNAPCRAFT_PART_INSTALL}/android-studio.tar.gz"
    build-packages:
      - wget
      - python3
    stage-packages:
      - libx11-6
      - libxau6
      - libxdmcp6
      - libxext6
      - libpng16-16
    build-attributes:
      - no-patchelf
