name: android-studio
version: '3.0'
summary: IDE for Android
description: |
  Android Studio provides the fastest tools for
  building apps on every type of Android device.

  World-class code editing, debugging, performance
  tooling, a flexible build system, and an instant
  build/deploy system all allow you to focus on
  building unique and high quality apps.

grade: stable
confinement: classic
architectures:
  - amd64

apps:
  android-studio:
    command: bin/studio.sh
    desktop: jetbrains-studio.desktop

parts:
  desktop:
    after:
      - android-studio
    plugin: dump
    source: .
    prime:
      - jetbrains-studio.desktop
  android-studio:
    plugin: dump
    source: https://dl.google.com/dl/android/studio/ide-zips/3.0.0.18/android-studio-ide-171.4408382-linux.zip

